import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import chalk from 'chalk';

interface InitOptions {
  template: string;
  auth: boolean;
  billing: boolean;
  git: boolean;
  packageManager: string;
}

const VALID_TEMPLATES = ['default', 'saas', 'crm', 'ecommerce'];

const DSL_TEMPLATES: Record<string, string> = {
  default: `entity User {
  id uuid
  name string
  email string
  role string
}

dashboard Overview {
  card TotalUsers from User
}
`,
  saas: `entity Organization {
  id uuid
  name string
  slug string
}

entity User {
  id uuid
  name string
  email string
  role string
}

entity Subscription {
  id uuid
  plan string
  status string
  user User @relation(User)
}

dashboard Admin {
  card TotalUsers from User
  card ActiveSubscriptions from Subscription where status == "active"
  chart bar PlanDistribution from Subscription by plan
}
`,
  crm: `entity Contact {
  id uuid
  firstName string
  lastName string
  email string
  company string
  status string
}

entity Deal {
  id uuid
  title string
  value money
  stage string
  contact Contact @relation(Contact)
}

dashboard Sales {
  card TotalContacts from Contact
  card OpenDeals from Deal where stage != "closed"
  chart bar DealValue from Deal by stage
  table ActiveDeals from Deal where stage != "closed" {
    column title label "Deal Name"
    column value label "Value"
    column stage label "Stage"
  }
}
`,
  ecommerce: `entity Product {
  id uuid
  name string
  price money
  sku string
  stock number
}

entity Order {
  id uuid
  total money
  status string
  product Product @relation(Product)
}

dashboard Store {
  card TotalProducts from Product
  card LowStock from Product where stock < 10
  chart line OrderTrend from Order by status
}
`,
};

/**
 * Initialize a new Nova project.
 */
export async function initCommand(projectName: string, options: InitOptions): Promise<void> {
  const { template, auth, billing, git, packageManager } = options;

  // Validate template
  if (!VALID_TEMPLATES.includes(template)) {
    console.error(chalk.red(`✖ Unknown template '${template}'. Valid: ${VALID_TEMPLATES.join(', ')}`));
    process.exit(2);
  }

  const targetDir = path.resolve(projectName);

  // Check if directory exists
  if (fs.existsSync(targetDir)) {
    const files = fs.readdirSync(targetDir);
    if (files.length > 0) {
      console.error(chalk.red(`✖ Directory '${projectName}' already exists and is not empty.`));
      process.exit(1);
    }
  }

  console.log(chalk.blue(`\n◴ Creating Nova project '${projectName}'...\n`));

  // Create directory structure
  fs.mkdirSync(targetDir, { recursive: true });
  fs.mkdirSync(path.join(targetDir, 'prisma'), { recursive: true });

  // Write DSL file
  const dslContent = DSL_TEMPLATES[template];
  fs.writeFileSync(path.join(targetDir, 'app.nova'), dslContent);
  console.log(chalk.green('  ✔ Created app.nova'));

  // Write nova.config.ts
  const configContent = generateConfig(template, auth, billing);
  fs.writeFileSync(path.join(targetDir, 'nova.config.ts'), configContent);
  console.log(chalk.green('  ✔ Created nova.config.ts'));

  // Write .env.example
  const envContent = generateEnvExample(auth, billing);
  fs.writeFileSync(path.join(targetDir, '.env.example'), envContent);
  console.log(chalk.green('  ✔ Created .env.example'));

  // Write .gitignore
  const gitignoreContent = `node_modules/\n.env\n.env.local\n.next/\nout/\ndist/\ngenerated-app/\n`;
  fs.writeFileSync(path.join(targetDir, '.gitignore'), gitcontent);
  console.log(chalk.green('  ✔ Created .gitignore'));

  // Write README
  const readmeContent = `# ${projectName}\n\nGenerated by Nova.\n\n## Getting Started\n\n1. Copy \`.env.example\` to \`.env\` and fill in values\n2. Run \`nova generate\` to compile the DSL\n3. Run \`cd generated-app && npm install && npm run dev\`\n`;
  fs.writeFileSync(path.join(targetDir, 'README.md'), readmeContent);
  console.log(chalk.green('  ✔ Created README.md'));

  // Initialize git
  if (git) {
    try {
      execSync('git init', { cwd: targetDir, stdio: 'ignore' });
      console.log(chalk.green('  ✔ Initialized git repository'));
    } catch {
      console.log(chalk.yellow('  ⚠ Git not found, skipping'));
    }
  }

  console.log(chalk.green(`\n✔ Project '${projectName}' created successfully!\n`));
  console.log(chalk.white('Next steps:'));
  console.log(chalk.gray(`  cd ${projectName}`));
  console.log(chalk.gray('  cp .env.example .env'));
  console.log(chalk.gray('  nova generate'));
  console.log('');
}

function generateConfig(template: string, auth: boolean, billing: boolean): string {
  const lines = [
    "import { defineConfig } from '@nova/cli';",
    '',
    'export default defineConfig({',
    `  source: 'app.nova',`,
    `  output: './generated-app',`,
    `  auth: ${auth},`,
    `  billing: ${billing},`,
    '});',
    '',
  ];
  return lines.join('\n');
}

function generateEnvExample(auth: boolean, billing: boolean): string {
  const lines = [
    '# Database',
    'DATABASE_URL="postgresql://user:password@localhost:5432/myapp"',
    '',
  ];

  if (auth) {
    lines.push(
      '# NextAuth',
      'NEXTAUTH_URL="http://localhost:3000"',
      'NEXTAUTH_SECRET="change-me-to-a-random-secret"',
      '',
      '# OAuth (optional)',
      'GOOGLE_CLIENT_ID=""',
      'GOOGLE_CLIENT_SECRET=""',
      'GITHUB_CLIENT_ID=""',
      'GITHUB_CLIENT_SECRET=""',
      '',
    );
  }

  if (billing) {
    lines.push(
      '# Stripe',
      'STRIPE_SECRET_KEY=""',
      'STRIPE_WEBHOOK_SECRET=""',
      'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=""',
      '',
    );
  }

  lines.push(
    '# AI (optional)',
    'OPENROUTER_API_KEY=""',
    '',
  );

  return lines.join('\n');
}
